<?php

return [
    'pedido' => 'Pedido',
    'fecha' => 'Fecha',
    'cliente' => 'Cliente',
    'num_pedido_cliente' => 'Nº Pedido Cliente',
    'titulo' => 'Título',
    'isbn_referencia' => 'ISBN/Referencia',
    'tirada' => 'Tirada',
    'fecha_archivos' => 'Fecha de archivos',
    'fecha_entrega' => 'Fecha de entrega',
    'fecha_plotters' => 'F.Plotters',
    'prueba_color' => 'Prueba color',
    'laminado' => 'Laminado',
    'modelo_caja' => 'Modelo Caja',
    'etiqueta' => 'Etiqueta',
    'uds_caja' => 'Uds x Caja',
    'distribucion' => 'Distribución',
    'cantidad' => 'Cantidad',
    'otros' => 'Otros',
    'subpedido' => 'Subpedido',
    'referencia' => 'Referencia',
    'uds' => 'Uds',
    'tarea' => 'Tarea',
    'fecha_inicio' => 'F.Inicio',
    'fecha_fin' => 'F.Fin',
    'asignado_a' => 'Asignado a',
    'estado' => 'Estado',
